`timescale 1ns / 1ps
`include "jpeg_params.vh"
`default_nettype none

module jpeg_top_bd #(
    parameter JPEG_NUM_DECODERS = 1,
    parameter DESC_FIFO_DEPTH_LOG2 = 4
) (
    input wire clk,
    input wire rst,

    /*
     * AXI lite MMIO subordinate interface
     */
    input  wire [`JPEG_MMIO_BITS_ADDR-1:0] s_axil_awaddr,
    input  wire [                     2:0] s_axil_awprot,
    input  wire                            s_axil_awvalid,
    output wire                            s_axil_awready,
    input  wire [                    63:0] s_axil_wdata,
    input  wire [                     7:0] s_axil_wstrb,
    input  wire                            s_axil_wvalid,
    output wire                            s_axil_wready,
    output wire [                     1:0] s_axil_bresp,
    output wire                            s_axil_bvalid,
    input  wire                            s_axil_bready,
    input  wire [`JPEG_MMIO_BITS_ADDR-1:0] s_axil_araddr,
    input  wire [                     2:0] s_axil_arprot,
    input  wire                            s_axil_arvalid,
    output wire                            s_axil_arready,
    output wire [                    63:0] s_axil_rdata,
    output wire [                     1:0] s_axil_rresp,
    output wire                            s_axil_rvalid,
    input  wire                            s_axil_rready,

    /*
     * AXI DMA manager interface
     */
    output wire [      `JPEG_DMA_BITS_ID-1:0] m_axi_awid,
    output wire [    `JPEG_DMA_BITS_ADDR-1:0] m_axi_awaddr,
    output wire [                        7:0] m_axi_awlen,
    output wire [                        2:0] m_axi_awsize,
    output wire [                        1:0] m_axi_awburst,
    output wire                               m_axi_awlock,
    output wire [                        3:0] m_axi_awcache,
    output wire [                        2:0] m_axi_awprot,
    output wire                               m_axi_awvalid,
    input  wire                               m_axi_awready,
    output wire [    `JPEG_DMA_BITS_DATA-1:0] m_axi_wdata,
    output wire [`JPEG_DMA_BITS_DATA / 8-1:0] m_axi_wstrb,
    output wire                               m_axi_wlast,
    output wire                               m_axi_wvalid,
    input  wire                               m_axi_wready,
    input  wire [      `JPEG_DMA_BITS_ID-1:0] m_axi_bid,
    input  wire [                        1:0] m_axi_bresp,
    input  wire                               m_axi_bvalid,
    output wire                               m_axi_bready,
    output wire [      `JPEG_DMA_BITS_ID-1:0] m_axi_arid,
    output wire [    `JPEG_DMA_BITS_ADDR-1:0] m_axi_araddr,
    output wire [                        7:0] m_axi_arlen,
    output wire [                        2:0] m_axi_arsize,
    output wire [                        1:0] m_axi_arburst,
    output wire                               m_axi_arlock,
    output wire [                        3:0] m_axi_arcache,
    output wire [                        2:0] m_axi_arprot,
    output wire                               m_axi_arvalid,
    input  wire                               m_axi_arready,
    input  wire [      `JPEG_DMA_BITS_ID-1:0] m_axi_rid,
    input  wire [    `JPEG_DMA_BITS_DATA-1:0] m_axi_rdata,
    input  wire [                        1:0] m_axi_rresp,
    input  wire                               m_axi_rlast,
    input  wire                               m_axi_rvalid,
    output wire                               m_axi_rready
);

  jpeg_top #(
      .JPEG_SUPPORT_WRITABLE_DHT(`JPEG_SUPPORT_WRITABLE_DHT),
      .JPEG_NUM_DECODERS(JPEG_NUM_DECODERS),
      .DESC_FIFO_DEPTH_LOG2(DESC_FIFO_DEPTH_LOG2),
      .AXI_DMA_ID_WIDTH(`JPEG_DMA_BITS_ID),
      .AXI_DMA_ADDR_WIDTH(`JPEG_DMA_BITS_ADDR),
      .AXI_DMA_DATA_WIDTH(`JPEG_DMA_BITS_DATA),
      .AXI_DMA_STRB_WIDTH(`JPEG_DMA_BITS_DATA / 8),
      .AXI_DMA_MAX_BURST_LEN(`JPEG_DMA_MAX_BURST_LEN),
      .AXIL_MMIO_ADDR_WIDTH(`JPEG_MMIO_BITS_ADDR)
  ) jpeg_top_inst (
      .clk(clk),
      .rst(rst),
      .s_axil_awaddr(s_axil_awaddr),
      .s_axil_awprot(s_axil_awprot),
      .s_axil_awvalid(s_axil_awvalid),
      .s_axil_awready(s_axil_awready),
      .s_axil_wdata(s_axil_wdata),
      .s_axil_wstrb(s_axil_wstrb),
      .s_axil_wvalid(s_axil_wvalid),
      .s_axil_wready(s_axil_wready),
      .s_axil_bresp(s_axil_bresp),
      .s_axil_bvalid(s_axil_bvalid),
      .s_axil_bready(s_axil_bready),
      .s_axil_araddr(s_axil_araddr),
      .s_axil_arprot(s_axil_arprot),
      .s_axil_arvalid(s_axil_arvalid),
      .s_axil_arready(s_axil_arready),
      .s_axil_rdata(s_axil_rdata),
      .s_axil_rresp(s_axil_rresp),
      .s_axil_rvalid(s_axil_rvalid),
      .s_axil_rready(s_axil_rready),
      .m_axi_awid(m_axi_awid),
      .m_axi_awaddr(m_axi_awaddr),
      .m_axi_awlen(m_axi_awlen),
      .m_axi_awsize(m_axi_awsize),
      .m_axi_awburst(m_axi_awburst),
      .m_axi_awlock(m_axi_awlock),
      .m_axi_awcache(m_axi_awcache),
      .m_axi_awprot(m_axi_awprot),
      .m_axi_awvalid(m_axi_awvalid),
      .m_axi_awready(m_axi_awready),
      .m_axi_wdata(m_axi_wdata),
      .m_axi_wstrb(m_axi_wstrb),
      .m_axi_wlast(m_axi_wlast),
      .m_axi_wvalid(m_axi_wvalid),
      .m_axi_wready(m_axi_wready),
      .m_axi_bid(m_axi_bid),
      .m_axi_bresp(m_axi_bresp),
      .m_axi_bvalid(m_axi_bvalid),
      .m_axi_bready(m_axi_bready),
      .m_axi_arid(m_axi_arid),
      .m_axi_araddr(m_axi_araddr),
      .m_axi_arlen(m_axi_arlen),
      .m_axi_arsize(m_axi_arsize),
      .m_axi_arburst(m_axi_arburst),
      .m_axi_arlock(m_axi_arlock),
      .m_axi_arcache(m_axi_arcache),
      .m_axi_arprot(m_axi_arprot),
      .m_axi_arvalid(m_axi_arvalid),
      .m_axi_arready(m_axi_arready),
      .m_axi_rid(m_axi_rid),
      .m_axi_rdata(m_axi_rdata),
      .m_axi_rresp(m_axi_rresp),
      .m_axi_rlast(m_axi_rlast),
      .m_axi_rvalid(m_axi_rvalid),
      .m_axi_rready(m_axi_rready)
  );

endmodule

`default_nettype wire
